"""
TCP ASTF (Advanced Stateful) traffic profile generator.

Generates a Python profile file that is uploaded to the remote
TRex client and loaded at runtime.
"""

PROFILE_TEMPLATE = '''\
"""TCP multi-core ASTF profile (auto-generated by trex-simulator)."""
from trex.astf.api import *


HTTP_REQ = (
    "GET /index.html HTTP/1.1\\r\\n"
    "Host: trex-test\\r\\n"
    "User-Agent: trex-simulator/1.0\\r\\n"
    "Accept: */*\\r\\n"
    "Connection: keep-alive\\r\\n"
    "\\r\\n"
)

HTTP_RESP_BODY = "X" * {payload_size}
HTTP_RESP = (
    "HTTP/1.1 200 OK\\r\\n"
    "Content-Type: text/plain\\r\\n"
    f"Content-Length: {{len(HTTP_RESP_BODY)}}\\r\\n"
    "Connection: keep-alive\\r\\n"
    "\\r\\n"
) + HTTP_RESP_BODY


def get_profile(tunables=None, **kwargs):
    # Each connection issues {reqs_per_conn} request/response cycles back-to-back
    # to sustain high bandwidth without paying TCP-handshake cost every transfer.
    prog_c = ASTFProgram()
    prog_c.connect()
    prog_c.set_var("loops", {reqs_per_conn})
    prog_c.set_label("again")
    prog_c.send(HTTP_REQ)
    prog_c.recv(len(HTTP_RESP))
    prog_c.jmp_nz("loops", "again")

    prog_s = ASTFProgram(side="server")
    prog_s.accept()
    prog_s.set_var("loops", {reqs_per_conn})
    prog_s.set_label("again")
    prog_s.recv(len(HTTP_REQ))
    prog_s.send(HTTP_RESP)
    prog_s.jmp_nz("loops", "again")

    ip_gen_c = ASTFIPGenDist(
        ip_range=["{client_ip_start}", "{client_ip_end}"],
        distribution="seq",
    )
    ip_gen_s = ASTFIPGenDist(
        ip_range=["{server_ip_start}", "{server_ip_end}"],
        distribution="seq",
    )
    ip_gen = ASTFIPGen(
        glob=ASTFIPGenGlobal(ip_offset="1.0.0.0"),
        dist_client=ip_gen_c,
        dist_server=ip_gen_s,
    )

    template = ASTFTemplate(
        client_template=ASTFTCPClientTemplate(
            program=prog_c,
            ip_gen=ip_gen,
            port=80,
            cps={cps},          # new connections per second per core
        ),
        server_template=ASTFTCPServerTemplate(
            program=prog_s,
            assoc=ASTFAssociation(rules=ASTFAssociationRule(port=80)),
        ),
    )

    return ASTFProfile(default_ip_gen=ip_gen, templates=template)
'''


def generate_profile(
    client_ip_start: str = "16.0.0.1",
    client_ip_end: str = "16.0.0.254",
    server_ip_start: str = "48.0.0.1",
    server_ip_end: str = "48.0.0.254",
    cps: int = 50000,
    payload_size: int = 65536,
    reqs_per_conn: int = 100,
) -> str:
    return PROFILE_TEMPLATE.format(
        client_ip_start=client_ip_start,
        client_ip_end=client_ip_end,
        server_ip_start=server_ip_start,
        server_ip_end=server_ip_end,
        cps=cps,
        payload_size=payload_size,
        reqs_per_conn=reqs_per_conn,
    )
